version: '3.7'

services:
  password_bot_telegram:
    build: ./
    command: ./wait-for-postgres.sh db ./password_bot_telegram
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=qwerty


  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - "5436:5432"
volumes:
  pgdbdata:
